### PR TITLE
Added qr code scanner

### LINKED ISSUE #19: QR code scanner
Build a QR code scanner in shealth app for scanning the QR code of the doctor.

### PR DESCRIPTION
**Pull request by Sayam06**
I added the qr code scanner in the patients screen. Just did a basic layout, the designing has to be done by you. Used a package for opening the URLs given by the barcode.

### CODE REVIEW

**Review by sidB67 — CHANGES_REQUESTED** [review]
Hi so the QR code scanner will be used to scan the doctor id which you can see when you log in as a doctor. So I wanted that when the scan gets complete and result gets updated can you call the addDoctor function give in provider/doctors.dart

**Comment by Sayam06** [comment]
> Hi so the QR code scanner will be used to scan the doctor id which you can see when you log in as a doctor. So I wanted that when the scan gets complete and result gets updated can you call the addDoctor function give in provider/doctors.dart

Will the barcode return an API link, calling which will give me the doctor details in JSON format? If this happens then adding the doctor details to the app will be easy. 

Can you give me a sample barcode for testing purpose?

**Comment by sidB67** [comment]
Hi the QR code will return a string which corresponds to a doctor id. We just need to send that token ID i have already made the functions. For sample QR code you can check the docID screen when you login as a doctor. For the function check the doctorsscreenpatient.dart

**Comment by Sayam06** [comment]
> Hi the QR code will return a string which corresponds to a doctor id. We just need to send that token ID i have already made the functions. For sample QR code you can check the docID screen when you login as a doctor. For the function check the doctorsscreenpatient.dart

So I need to send the doctor id to your backend and get the doctor info, and then add it in using the addDoctor function, right?

**Comment by sidB67** [comment]
Just use the addDoctor function it will link the doctor to the patient rest doctor info fetching and all is taken care of

**Comment by Sayam06** [comment]
Alright, so I get the doctor id from the qr code and then send it to the addDoctor function?

**Comment by sidB67** [comment]
yup

**Comment by Sayam06** [comment]
@sidB67 check now, I created a new function which will take the doctor id from the qr code and call the addDoctor function. 

Please insert the auth token to make it functional.

**Review by sidB67 — APPROVED** [review]

**Pull request merged**
